import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Homepage from './Homepage'
import Sidebar from '@/components/Sidebar';

import { useSession } from 'next-auth/react'
import Login from '@/components/Login'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  const { data: session } = useSession();
  
  return (
    <>
      <Head>
        <title>ChatGPT Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!session ? <Login /> : <main className='flex'>
        <div className='bg-[#202123] max-w-sm h-screen overflow-y-auto md:min-w-[20rem]'>
          <Sidebar />
        </div>
        <div className='bg-[#343541] flex-1'>
          <Homepage />
       </div>
      </main>}
    </>
  )
}
